---
switch_config_apply: false  # noqa: var-naming[no-role-prefix]
switch_config_allowed_states:  # noqa: var-naming[no-role-prefix]
  - merged
switch_config_resources: {}  # noqa: var-naming[no-role-prefix]
