---
- name: Import validation phase
  ansible.builtin.import_tasks: validate.yml

- name: Import planning phase
  ansible.builtin.import_tasks: plan.yml

- name: Import collection phase
  ansible.builtin.import_tasks: collect.yml

- name: Import parsing phase
  ansible.builtin.import_tasks: parse.yml
