"""Focused Phase 3 tests for PVE template build parameterization."""

from __future__ import annotations

import copy
import os
import subprocess
from pathlib import Path

import pytest

from scripts.pve_inventory.io import load_yaml
from scripts.pve_inventory.model import build_model
from scripts.pve_inventory.render import render_outputs
from scripts.pve_inventory.errors import ValidationError
from scripts.pve_inventory.validation import validate_cluster


ROOT = Path(__file__).resolve().parents[2]
CLUSTER_PATH = ROOT / "inventory" / "pve-cluster.yml"


def cluster_state() -> dict[str, object]:
    return validate_cluster(load_yaml(CLUSTER_PATH))


def template_env_text() -> str:
    model = build_model(cluster_state(), [])
    return render_outputs(model)["template_build_env"]


def test_template_build_env_uses_if_unset_guards() -> None:
    text = template_env_text()
    assert text.startswith("# Generated by scripts.pve_inventory.cli; source from build-template.sh.\n")
    assert "if [ -z \"${TEMPLATE_VMID+x}\" ]; then TEMPLATE_VMID='9001'; fi" in text
    assert "if [ -z \"${BUILD_BRIDGE+x}\" ]; then BUILD_BRIDGE='br_dev'; fi" in text
    assert text.count("if [ -z \"") == 15


def test_template_build_env_excludes_forbidden_repository_details() -> None:
    text = template_env_text()
    forbidden = (
        "PVE_HOST",
        "PVE_USER",
        "/usr/local/sbin/astra-pve-template-build",
        "/var/cache/astra/packer",
        "^[A-Za-z0-9][A-Za-z0-9._-]+$",
    )
    for item in forbidden:
        assert item not in text


def test_template_build_env_honors_caller_overrides(tmp_path: Path) -> None:
    env_file = tmp_path / "template-build.env"
    env_file.write_text(template_env_text(), encoding="utf-8")

    result = subprocess.run(
        [
            "bash",
            "-lc",
            f'IMAGE_URL="override-url"; TEMPLATE_VMID="9999"; . "{env_file}"; printf "%s|%s" "$IMAGE_URL" "$TEMPLATE_VMID"',
        ],
        check=True,
        capture_output=True,
        text=True,
    )
    assert result.stdout == "override-url|9999"


def test_template_build_script_shell_quotes_remote_args(tmp_path: Path) -> None:
    ssh_bin = tmp_path / "ssh"
    capture_path = tmp_path / "ssh-argv.txt"
    ssh_bin.write_text(
        "#!/usr/bin/env bash\n"
        "set -euo pipefail\n"
        "printf '%s\\n' \"$@\" > \"${SSH_CAPTURE}\"\n",
        encoding="utf-8",
    )
    ssh_bin.chmod(0o755)

    script = ROOT / "infra" / "packer" / "proxmox" / "debian-13" / "build-template.sh"
    env = os.environ | {
        "PATH": f"{tmp_path}{os.pathsep}{os.environ['PATH']}",
        "SSH_CAPTURE": str(capture_path),
        "PVE_HOST": "pve-01.example.invalid",
        "PVE_USER": "pve-ops",
        "TEMPLATE_VMID": "9001",
        "TEMPLATE_NAME": "debian-13-tmpl-20260621",
        "IMAGE_URL_PREFIX": "https://images.example.invalid/",
        "IMAGE_URL": "https://images.example.invalid/debian'$(touch /tmp/pwned);`id`.qcow2",
        "IMAGE_SHA512": "a" * 128,
        "IMPORT_STORAGE": "local",
        "DISK_STORAGE": "fast-nvme",
        "BUILD_DOMAIN": "build.example.invalid",
        "APT_MIRROR": "https://deb.debian.org/debian",
        "APT_SECURITY_MIRROR": "https://security.debian.org/debian-security",
        "TIMEZONE": "Etc/UTC",
        "LOCALE": "en_US.UTF-8",
        "CIUSER": "ci'user",
        "NAMESERVER": "192.0.2.53",
        "BUILD_BRIDGE": "br_dev",
        "FORCE_REPLACE": "true",
        "TEMPLATE_DEBUG": "true",
    }

    subprocess.run(["bash", str(script)], check=True, env=env, capture_output=True, text=True)

    host, remote_command = capture_path.read_text(encoding="utf-8").splitlines()
    assert host == "pve-ops@pve-01.example.invalid"
    assert remote_command.startswith("'sudo' '-n' '/usr/local/sbin/astra-pve-template-build'")
    assert "--image-url" in remote_command
    assert "'https://images.example.invalid/debian'\\''$(touch /tmp/pwned);`id`.qcow2'" in remote_command
    assert "--ciuser" in remote_command
    assert "'ci'\\''user'" in remote_command
    assert remote_command.endswith("'--force' '--debug'")


def test_template_build_script_rejects_shell_unsafe_template_name(tmp_path: Path) -> None:
    ssh_bin = tmp_path / "ssh"
    ssh_bin.write_text("#!/usr/bin/env bash\nexit 99\n", encoding="utf-8")
    ssh_bin.chmod(0o755)

    script = ROOT / "infra" / "packer" / "proxmox" / "debian-13" / "build-template.sh"
    env = os.environ | {
        "PATH": f"{tmp_path}{os.pathsep}{os.environ['PATH']}",
        "PVE_HOST": "pve-01.example.invalid",
        "TEMPLATE_VMID": "9001",
        "TEMPLATE_NAME": "bad template name",
        "IMAGE_URL_PREFIX": "https://images.example.invalid/",
        "IMAGE_URL": "https://images.example.invalid/debian.qcow2",
        "IMAGE_SHA512": "a" * 128,
        "IMPORT_STORAGE": "local",
        "DISK_STORAGE": "fast-nvme",
        "BUILD_DOMAIN": "build.example.invalid",
        "APT_MIRROR": "https://deb.debian.org/debian",
        "APT_SECURITY_MIRROR": "https://security.debian.org/debian-security",
        "TIMEZONE": "Etc/UTC",
        "LOCALE": "en_US.UTF-8",
        "CIUSER": "ci",
        "NAMESERVER": "192.0.2.53",
        "BUILD_BRIDGE": "br_dev",
    }

    result = subprocess.run(["bash", str(script)], env=env, capture_output=True, text=True)

    assert result.returncode == 1
    assert "template name must match the conservative template regex" in result.stderr


def test_validation_rejects_unknown_template_build_keys() -> None:
    doc = copy.deepcopy(load_yaml(CLUSTER_PATH))
    doc["cluster"]["automation"]["template_build"]["unexpected"] = "boom"
    with pytest.raises(ValidationError, match="unknown keys"):
        validate_cluster(doc)


@pytest.mark.parametrize(
    ("field", "value", "message"),
    [
        ("image_url", "https://example.invalid/not-debian.qcow2", "must start with image_url_prefix"),
        ("build_bridge", "storage", "must reference an attachable network bridge"),
        ("nameserver", "not-an-ip", "must be a valid IP address"),
    ],
)
def test_validation_rejects_phase3_template_build_inputs(field: str, value: str, message: str) -> None:
    doc = copy.deepcopy(load_yaml(CLUSTER_PATH))
    doc["cluster"]["automation"]["template_build"][field] = value
    with pytest.raises(ValidationError, match=message):
        validate_cluster(doc)
