---
all:
  children:
    opnsense:
      hosts:
        soter:
          ansible_connection: local
          ansible_host: localhost
          ansible_python_interpreter: "{{ ansible_playbook_python }}"
          opnsense_api_host: 10.1.0.254
          opnsense_fqdn: soter.mgmt.clemon.cis
    switches:
      hosts:
        sw-core:
          ansible_connection: local
          ansible_host: 10.1.0.20
          ansible_python_interpreter: "{{ ansible_playbook_python }}"
          switch_model_hint: SKS8300-12X
