"""Repository-owned read-only PVE API contract."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class PveReadOnlyApi(Protocol):
    def cluster_status(self) -> Any: ...

    def nodes(self) -> Any: ...

    def node_status(self, node: str) -> Any: ...

    def node_network(self, node: str) -> Any: ...

    def node_storage(self, node: str) -> Any: ...

    def cluster_vm_resources(self) -> Any: ...

    def vms(self, node: str) -> Any: ...

    def vm_status(self, node: str, vmid: int) -> Any: ...

    def vm_config(self, node: str, vmid: int) -> Any: ...

    def pci_mappings(self) -> Any: ...

    def pci_mapping_detail(self, mapping_name: str) -> Any: ...

    def ha_status(self) -> Any: ...

    def ceph_status(self) -> Any: ...


__all__ = ["PveReadOnlyApi"]
